# .github/workflows/main.yml

name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print Secrets
      run: |
        echo "HOST: ${{ secrets.HOST }}"
        echo "USERNAME: ${{ secrets.USERNAME }}"
        echo "PASSWORD: ${{ secrets.PASSWORD }}"
        echo "PORT: ${{ secrets.PORT }}"  
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        pwd
        ls
        npm install

    - name: Deploy to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "LinkhubBackend/*"
        target: "LinkhubBackend"
    - name: Install sshpass
      run: |
          sudo apt-get update
          sudo apt-get install -y sshpass    
    - name: Execute Commands on VPS
      run: |
       sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /root/workplace/LinkhubBackend && npm install && pm2 restart backend'    
