# .github/workflows/main.yml

name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print Secrets
      run: |
        echo "HOST: ${{ secrets.HOST }}"
        echo "USERNAME: ${{ secrets.USERNAME }}"
        echo "PASSWORD: ${{ secrets.PASSWORD }}"
        echo "PORT: ${{ secrets.PORT }}"  
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        pwd
        ls
        npm install
    - name: Run a multi-line script
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/
    - name: Deploy to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "deploy.tar"
        target: "/root/workspace/LinkhubBackend/"
    - name: Extract files on VPS
      run: |
        sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /root/workspace/LinkhubBackend && tar -xvf deploy.tar'           
    - name: Execute Commands on VPS
      run: |
       sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /root/workplace/LinkhubBackend && npm install && pm2 restart backend'    
